@todo_id = 1
###

// Needs https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

//Create regular user
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "username" : "user",
    "password" : "Hunter2!"
}

###

// Authenticate as regular user
# @name LoginRegularUser
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "username" : "user",
    "password" : "Hunter2!"
}

@token = {{LoginRegularUser.response.body.token}}
###

// New Todo
POST http://localhost:5000/api/todos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name" : "Write unit tests.",
    "IsComplete" : false
}

###

// Get all todos with auth
GET http://localhost:5000/api/todos
Authorization: Bearer {{token}}


###


// Get a single todo
GET http://localhost:5000/api/todos/{{todo_id}}
Authorization: Bearer {{token}}

###

// Authenticate as an admin user
# @name LoginAdminUser
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Pass123456!"
}

###

// Delete Todo. must be authenticated as admim

@admintoken = {{LoginAdminUser.response.body.token}}

DELETE http://localhost:5000/api/todos/{{todo_id}}
Authorization: Bearer {{admintoken}}
